//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KolejUygulama.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Brans
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Brans()
        {
            this.Ogretmenler = new HashSet<Ogretmenler>();
            this.Sinavlar = new HashSet<Sinavlar>();
        }
    
        public int Id { get; set; }
        public string BransAdi { get; set; }
        public Nullable<short> DersSaati { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ogretmenler> Ogretmenler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sinavlar> Sinavlar { get; set; }
    }
}
