//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KolejUygulama.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DersPlani
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DersPlani()
        {
            this.Yoklama = new HashSet<Yoklama>();
        }
    
        public int id { get; set; }
        public int OgretmenId { get; set; }
        public int SaatId { get; set; }
        public int SubeId { get; set; }
        public System.DateTime Tarih { get; set; }
    
        public virtual Ogretmenler Ogretmenler { get; set; }
        public virtual Saat Saat { get; set; }
        public virtual Sube Sube { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yoklama> Yoklama { get; set; }
    }
}
