//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sinavlar
    {
        public int SınavId { get; set; }
        public Nullable<int> OgrenciId { get; set; }
        public Nullable<int> BransId { get; set; }
        public Nullable<short> Sınav1 { get; set; }
        public Nullable<short> Sınav2 { get; set; }
        public Nullable<short> Proje { get; set; }
    
        public virtual Brans Brans { get; set; }
        public virtual Ogrenciler Ogrenciler { get; set; }
    }
}
